name: Greetings

on: 
 # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thank you for generating an issue to this project! Please wait while we get back to you.'' first issue'
        pr-message: 'We love Pull Requests! Thank you for contributing, however you will have to wait we check with your PR. '' first pr'
